# Generated by Django 5.2.1 on 2025-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Proj", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
