# Generated by Django 5.2.1 on 2025-06-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Proj", "0003_alter_produto_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="Estoque",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
