# Generated by Django 5.2.1 on 2025-06-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Proj", "0004_produto_estoque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="Estoque",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="produto",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="product/"),
        ),
    ]
